version: "3.8"
services:
  MonEtabPostgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Mon_Etab
    ports:
      - 5432:5432